shiny:
  proxy:
    title: Cloud Morris - Data Visualization using Shiny and AWS
    #title: tst
    logo-url: https://lh3.googleusercontent.com/-pNx_tnWyziE/WDHFwB0lYPI/AAAAAAAAgLQ/9sjBtXOkkUghGICU1Loj106SQb8atfVyACJoC/w346-h265/mm.png
    #logo-url: http://www.openanalytics.eu/sites/www.openanalytics.eu/themes/oa/logo.png
    landing-page: /
    heartbeat-rate: 80000
    heartbeat-timeout: 200000
    port: 8080
    authentication: simple
    admin-groups: admins
    #Simple auth configuration
    users:
     - name: rachael
       password: morris
       groups: users, admins
     - name: rhonda
       password: morris
       groups: users, admins
     - name: jason
       password: rich
       groups: users, admins
     - name: cam 
       password: miller
       groups: users, admins
     - name: gram 
       password: miller
       groups: users, admins
     - name: adam
       password: tessone
       groups: users, admins
     - name: louie
       password: menard
       groups: admins, users 
     - name: jeff 
       password: snyder
       groups: admins, users 
     - name: mike
       password: morris
       groups: admins, users 
    docker:
      cert-path: /home/none
      url: http://localhost:2375
      host: 127.0.0.1
      port-range-start: 20000
  apps:
  - name: 01_hello
    display-name: DEMO ~ Hello Application
    description: Application which demonstrates the basics of a Shiny app
    docker-cmd: ["R", "-e shinyproxy::run_01_hello()"]
    docker-image: openanalytics/shinyproxy-demo
    groups: admins, users
  - name: 02_Euler 
    display-name: DEMO ~ Euler's e in arbitrary precision
    description:  The number e is an important mathematical constant that is the base of the natural logarithm. It is approximately equal to 2.71828, and is the limit of (1 + 1/n)n as n approaches infinity, an expression that arises in the study of compound interest. It can also be calculated as the sum of the infinite series.
    docker-cmd: ["R", "-e shiny::runApp('/root/euler')"] 
    docker-image: temp
    groups: users, admins
  - name: 06_tabset
    display-name: DEMO ~ Tab Application 
    description: Application which demonstrates the basics of a Shiny app. The content displays basic probability distributions(a mathematical description of a random phenomenon in terms of the probabilities of events) and the code used to run the application.
    docker-cmd: ["R", "-e shinyproxy::run_06_tabsets()"]
    docker-image: openanalytics/shinyproxy-demo 
    groups: users, admins
  - name: make_your_own 
    display-name: Make your own dash
    description: Application which dynamic creates dashboards on the fly
    docker-cmd:   ["R", "-e shiny::runApp('/root/sb')"]
    docker-image: mikemorris89/sbdr
    groups: users, admins
logging:
  file:
    shinyproxy.log
