#!/bin/bash	

#Build, tag, and push Docker image
#Now that your repository exists, you can push a Docker image by following these steps:
#Successfully created repository
#816481233179.dkr.ecr.us-east-1.amazonaws.com/morris/repo
#Prerequisites: If you haven't installed the AWS CLI, please follow the instructions here to do so. If you haven't installed Docker, please follow the instructions here to do so.
#1) Retrieve the docker login command that you can use to authenticate your Docker client to your registry:
aws ecr get-login --region us-east-1

#2) Run the docker login command that was returned in the previous step.
#3) Build your Docker image using the following command. For information on building a Docker file from scratch see the instructions here. You can skip this step if your image is already built:
docker build -t morris/repo .

#4) After the build completes, tag your image so you can push the image to this repository:
docker tag morris/repo:latest 816481233179.dkr.ecr.us-east-1.amazonaws.com/morris/repo:latest

#5) Run the following command to push this image to your newly created AWS repository:
docker push 816481233179.dkr.ecr.us-east-1.amazonaws.com/morris/repo:latest
